[workspace]
authors = ["Keeney <nkeeney@oceanics.io>"]
channels = ["conda-forge"]
name = "helmholtz-lobsters"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
